name: Container job sample 
on:
  push:

jobs:
    my_first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Use local my-action
          uses: ./github-actions-apps-token